services:

  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - "1221:1221"
    user: "${UID}:${GID}"      
    environment:
      - AUTH_SECRET=UyNkCcvmY3j3qAuQPm1eFW3nxQ3zpVZEC7vAYwRdfu9SHgLV
      - APP_BASE_URL=http://localhost:1221
    volumes:
      - ./papra/data:/app/app-data
